### PR TITLE
Added a fix to allow for spaces in app path.

### PR DESCRIPTION
**Pull request by paymand**

### CODE REVIEW

**Comment by jlipps** [comment]
@OniOni can you review/merge or give me write access? :-)

**Comment by OniOni** [comment]
Sorry @jlipps and @paymand. Notifications for this repo seemed to have gone under my radar recently. I'll review this asap. Also give you write access @jlipps.

**Comment by OniOni** [comment]
Thanls @paymand !

**Comment by OniOni** [comment]
Published in version 0.1.5.

**Pull request merged**
